Project = "demo"
Company = "jasperxu.com"
Developer = "JasperXu"

# 是否调试状态
IsDebug = true

# 是否启用HTTPS。server.crt和server.key放到根目录即可
IsHTTPS = false

# 访问地址
URL = "http://127.0.0.1:8080/"

# 运行端口
Port = "8080"

# 错误信息本地化
I18nNoAccessRights = "没有访问权限"
I18nFileNotFound = "文件不存在"

I18nUploadError = "上传错误"
I18nProhibitExt = "禁止上传的文件类型"
I18nCreateError = "创建文件失败"
I18nSaveError = "保存文件失败"
I18nUploadSuccess = "上传成功"

I18nDeleteError = "删除失败"
I18nDeleteSuccess = "删除成功"

# 禁止上传的文件后缀
ProhibitExt = [".exe", ".bat", ".sh", ".js" ]

# 允许最大文件 100M = 100*1024*1024
MaxFileSize = 104857600

# 为空表示任何人都可以读文件，否则在Get中需加入?ReadKey
ReadKey = ""

# 为空表示任何人都可以写文件，否则需在Post的URL中需加入?WriteKey 或在post表单中加入key参数值为WriteKey。
WriteKey = ""

